apiVersion: v2
name: belizechain
description: BelizeChain - Sovereign Blockchain Infrastructure for Belize
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - blockchain
  - substrate
  - polkadot
  - federated-learning
  - quantum-computing
  - belize
home: https://github.com/BelizeChain/infra
sources:
  - https://github.com/BelizeChain/infra
maintainers:
  - name: BelizeChain Team
    email: dev@belizechain.org
dependencies: []
